# Define the stages of the pipeline
stages:
  - build
  - test
  - release


# Job to build the project using Maven
build-project:
  stage: build
  image: maven:latest
  script:
    - mvn clean package  # Clean and build the Maven project
  artifacts:
    paths:
      - target/*.jar    # Upload the generated JAR file as an artifact

  # Job to run unit tests
test-project:
  stage: test
  image: maven:latest
  needs:
    - job: build-project
  script:
    - mvn test -D java.awt.headless=true # Run Maven tests
  artifacts:
    when: always        # Upload test results as artifacts
    reports:
      junit:
        - target/surefire-reports/*.xml  # Capture test results in JUnit XML format

release-project:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: test-project
    - job: build-project
      artifacts: true
  script:
    - echo "creating release"
  rules:                          
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  release:
    tag_name: 'v0.$CI_PIPELINE_IID' 
    description: 'v0.$CI_PIPELINE_IID'   
    ref: '$CI_COMMIT_SHA'
    assets:
      links:
        - name: 'binary'
          url: 'https://gitlab.com/api/v4/projects/57106016/jobs/artifacts/main/raw/review/index.html?job=build'