# Define the stages of the pipeline
stages:
  - build
  - test
  - publish


# Job to build the project using Maven
build-project:
  stage: build
  image: maven:latest
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar

# Job to run unit tests
test-project:
  stage: test
  image: maven:latest
  needs:
    - job: build-project
  script:
    - mvn test -D java.awt.headless=true
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/*.xml

# Job to publish the project to a Maven repository
publish-project:
  stage: publish
  image: maven:latest
  only:
    refs:
      - master
  needs:
    - job: build-project
    - job: test-project
  script:
    - mvn clean deploy