# Define the stages of the pipeline
stages:
  - build
  - test
  - publish


# Job to build the project using Maven
build-project:
  stage: build
  image: maven:latest
  script:
    - mvn clean package  # Clean and build the Maven project
  artifacts:
    paths:
      - target/*.jar    # Upload the generated JAR file as an artifact

  # Job to run unit tests
test-project:
  stage: test
  image: maven:latest
  needs:
    - job: build-project
  script:
    - mvn test -D java.awt.headless=true # Run Maven tests
  artifacts:
    when: always        # Upload test results as artifacts
    reports:
      junit:
        - target/surefire-reports/*.xml  # Capture test results in JUnit XML format

publish-project:
  stage: publish
  image: maven:latest
  needs:
    - job: build-project
    - job: test-project
  script:
    - mvn clean deploy  # Clean and build the Maven project