name: Publish

on:
  workflow_dispatch:
  release:
    types: [created]
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Deploy to GitHub
        run: mvn --batch-mode -P github deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}